spring:
  main:
    banner-mode: "off"
  application:
    name: backend
  mongodb:
    uri: mongodb+srv://n07:LTW_2026@clustertest.xg7jkii.mongodb.net/pharmagentdb.ct01?appName=ClusterTest

logging:
  level:
    root: warn

management:
  endpoints:
    web:
      exposure:
        include: health